"""Add IdentityReconciliation

Revision ID: d267aa60a761
Revises: 9e5c155c795d
Create Date: 2026-09-22 11:13:42.891915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd267aa60a761'
down_revision: Union[str, Sequence[str], None] = '9e5c155c795d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_reconciliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_patient_id', sa.Integer(), nullable=False),
    sa.Column('candidate_patient_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'CONFIRMED_MATCH', 'REJECTED_MATCH', name='identityreconciliationstatus'), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('components_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_patient_id', 'candidate_patient_id', name='uq_identity_reconciliation_source_candidate')
    )
    op.create_index(op.f('ix_identity_reconciliations_candidate_patient_id'), 'identity_reconciliations', ['candidate_patient_id'], unique=False)
    op.create_index(op.f('ix_identity_reconciliations_id'), 'identity_reconciliations', ['id'], unique=False)
    op.create_index(op.f('ix_identity_reconciliations_source_patient_id'), 'identity_reconciliations', ['source_patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identity_reconciliations_source_patient_id'), table_name='identity_reconciliations')
    op.drop_index(op.f('ix_identity_reconciliations_id'), table_name='identity_reconciliations')
    op.drop_index(op.f('ix_identity_reconciliations_candidate_patient_id'), table_name='identity_reconciliations')
    op.drop_table('identity_reconciliations')
    # ### end Alembic commands ###
